name: Build

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'haskell-dev'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Check out
      uses: actions/checkout@v3

    - name: Build package
      run: stack build 
